   <p class="error"><?php echo $this->errorMessage('loginForm'); ?></p>   
<form class="form-inline"  action="<?php echo $this->link('index', 'login'); ?>" methode="post">
     
    <input type="text" name="email" class="input-medium" placeholder="Identifiant(votre email)">
    <input type="password" name="password" class="input-small" placeholder="Mot de passe">
   <!--
   <label class="checkbox">
    <input type="checkbox"> Remember me
    </label>
   -->
    <button type="submit" class="btn btn-primary">Sign in</button>
    </form>

<p>
    <a href="<?php echo $this->link('index','login'); 
    
      //Zend_Debug::dump($this->log);
    ?>">Login</a>
</p>
