<?php $this->title='Mot de passe oublié';
       
  ?>




<style type="text/css">
* { font-family: Verdana; font-size: 96%; }
label { width: 14em; float: left; }
label.error { float: none; color: red; padding-left: .3em; vertical-align: top; }
p { clear: both; }
.submit { margin-left: 6em; }
em { font-weight: bold; padding-left: 4em; vertical-align: top; }

</style>
  
  


  
    <form class="form-inline" action="<?php echo $this->link('user','checkpassword'); ?>" method="post">
    <input type="text" class="input-large" placeholder="Email" required="true" name="email">
    
    <button type="submit" class="btn btn-primary">    <i class="icon-ok icon-white"></i></button>
    </form>


