<!-- Confirm CSS files -->
<link type='text/css' href='<?php echo $this->baseUrl() ?>/js/lib/simple-modal/css/confirm.css' rel='stylesheet' media='screen' />

<?php
$this->title = 'les utilisateurs';
?>
<style>
   body .modal {
    width: 350px;
       margin-left: -280px;
       
       
   }
   
   
       

</style>


<script type='text/javascript' src='<?php echo $this->baseUrl() ?>/js/lib/simple-modal/jquery.simplemodal.js'></script>
<script type='text/javascript' src='<?php echo $this->baseUrl() ?>/js/lib/simple-modal/confirm.js'></script>


<!--<script type="text/javascript" src="<?php //echo $this->baseUrl() ?>/js/delUsers.js"></script>-->

 
<form methode="post">
<table class="table table-striped table-hover">
    <tr>
        <th>Login</th>
        <th>nom</th>
         <th>statut</th>
        <th>rôle</th>
       <th>&nbsp;</th>
       <!--<th>&nbsp;</th>-->
       <th><input type="checkbox" name="all" id="all"/></th>
    </tr>
    
<?php foreach($this->users as $cle=>$a) : ?>
    <tr>
        <td> <?php echo $this->escape($a->email);?></td>
        <td><?php echo $this->escape($a->nom);?></td>
        <td><?php 
        $actif=( $a->actif==1 ) ? 'Activé': 'Non activé';
    
        echo $this->escape($actif);
        
        ?></td>
        <td><?php echo $this->escape($a->role);?></td>
        <td>
            <a href="<?php echo $this->url(array('controller'=>'user',
                'action'=>'update', 'id'=>$a->id));?>" class="btn">    <i class="icon-edit "></i></a>
         &nbsp;&nbsp;
         
         
         
   
         
         
         
            <a  href="<?php echo $this->url(array('controller'=>'user',
                'action'=>'delete', 'id'=>$a->id));?>" class="btn" > <i class="icon-remove-circle"></i></a>

        </td>
        <td><input type="checkbox" name="ids[]" value="<?php echo $this->escape($a->id);?>"/></td>
    </tr>
<?php endforeach; ?>
    
   
</table>
    
     </form>
<br/>
<p><?php echo "il y a <b> ",  count($this->users),"</b> utilisateurs"; ?></p>


<p><a href="<?php echo $this->url(array('controller'=>'index',
        'action'=>'index'));?>"><i class="icon-home"></i></a>&nbsp;&nbsp;|&nbsp;&nbsp;

<a href="<?php echo $this->url(array('controller'=>'user',
        'action'=>'index'));?>"><i class="icon-pencil"></i></a></p>

    
<!--<a type="button" class="btn" style="width:20%;" href="#test_modal" data-toggle="modal">Add Image</a>-->

<!--<a href="#test_modal" data-toggle="modal">Add Image</a>-->

<a type="button" class="btn" style="width:30%;" href="#test_modal" id="selec" data-toggle="modal">clic</a>

      

         <!--end-->
         
         
         <div id="resultat"></div>
         
         

         
<div id='confirm-dialog'>
  
   <input type='button' name='confirm' class='confirm' value='Demo'/> or <a href='/user/userlist' class='confirm'>Demo</a><!-- lien de confirmation -->
</div>
		

		<!-- modal content -->
<div id='confirm'>
 <div class='header'><span>Confirm</span></div>
 <div class='message'></div>
 <div class='buttons'>
 <div class='no simplemodal-close'>Non</div><div class='yes'>Oui</div>
 </div>
</div>
