<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="armel">

        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() ?>/css/bootstrap/css/bootstrap.css">
       
         <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
         <script src="<?php echo $this->baseUrl() ?>/css/bootstrap/js/bootstrap.js"></script>
         <script src="https://raw.github.com/makeusabrew/bootbox/v3.2.0/bootbox.min.js"></script>

        <title><?php echo $this->escape($this->title); ?></title>
    </head>
    <body>


        <div class="container">

            <!-- Main hero unit for a primary marketing message or call to action -->
            <div class="hero-unit">
                <p><a href="<?php echo $this->link('index','index'); ?>"><i class="icon-home"></i></a></p>
                <h1><?php //echo $this->escape($this->title); ?></h1>
                <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
                <p><a href="#" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
               
            </div>

            <!-- Example row of columns -->
            <div class="row">
                <div class="span4">
                    
                    <h2>Connexion</h2>
                    
                    <!--<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                    <p><a class="btn" href="#">View details &raquo;</a></p>
                    -->
                    <p><!--##########affichahe du form de connexion ########## -->
                        <?php 
                        
                       //  echo $this->partial('index/login.phtml');
                        // echo $this->layout()->loginForm;
                        // echo $this->placeholder('loginForm');
                          echo $this->loggedInAs();
                         ?>
                        
                    </p>
                </div>
                <div class="span4">
                    <h2>Heading</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                    <p><a class="btn" href="#">View details &raquo;</a></p>
                </div>
                <div class="span4">
                    <h2>Heading</h2>
                    <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
                    <p><a class="btn" href="#">View details &raquo;</a></p>
                </div>
            </div>


           <!--     corps du layout         -->
            <div>

                <?php echo $this->layout()->content; ?>

            </div>
            <hr>
            <footer>
                <p>&copy; Company 2013</p>
            </footer>

        </div> <!-- /container -->




















        
    </body>
</html>
